name: tracker
services:
  be:
    image: delivery-tracker:latest
    depends_on:
      - questdb
      - grafana
    env_file:
      - .env

  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    ports:
      - "8812:8812"
      - "9000:9000" # Web Console
    volumes:
      - questdb-data:/root/.questdb/db
    environment:
      QDB_PG_USER: ${QDB_PG_USER}
      QDB_PG_PASSWORD: ${QDB_PG_PASSWORD}
      QDB_PG_PORT: 8812
      QDB_PG_HOST: 0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_DATASOURCES_QUESTDB_HOST: questdb
      GF_DATASOURCES_QUESTDB_USER: ${GF_DATASOURCES_QUESTDB_USER}
      GF_DATASOURCES_QUESTDB_PASSWORD: ${GF_DATASOURCES_QUESTDB_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - questdb
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "4001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - be

volumes:
  questdb-data:
  grafana-data:
